/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    DemoPanel: typeof import('./src/components/DemoPanel.vue')['default']
    GlCanvas: typeof import('./src/components/GlCanvas.vue')['default']
    RenderModeMenu: typeof import('./src/components/RenderModeMenu.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
